version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
