package:
  name: model_analyzer
  version: "0.0.3"

build:
  noarch: python

requirements:
  build:
    - python=3.7

  run:
    - python=3.7
    - bzip2
    - gurobi

test:
  imports:
    - model_analyzer
