[tox]
envlist =
    py{310,311,312}-gurobipy{110,120,130}
    py{313}-gurobipy{120,130}
isolated_build = True

[testenv]
deps =
    gurobipy110: gurobipy==11.0.3
    gurobipy120: gurobipy==12.0.3
    gurobipy130: gurobipy==13.0.0
commands =
    python -m unittest discover -b
