# Build a universal wheel and store it as an artifact

name: Build wheel

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-wheel:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: Build
        run: uv build
      - name: File listing
        run: |
          ls -R
      - name: Archive wheel as artifact
        uses: actions/upload-artifact@v7
        with:
          name: wheel-artifact
          path: dist/*.whl
      - name: Archive sdist as artifact
        uses: actions/upload-artifact@v7
        with:
          name: sdist-artifact
          path: dist/*.tar.gz
