# Build a universal wheel and store it as an artifact

name: Build wheel

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-wheel:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build
      - name: Build wheel and sdist
        run: |
          python -m build
      - name: File listing
        run: |
          ls -R
      - name: Archive wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-artifact
          path: dist/*.whl
      - name: Archive sdist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist-artifact
          path: dist/*.tar.gz
