# The docs should build without warnings from sphinx

name: Docs build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  doc-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: Build docs (fail on warnings)
        run: uv run --group=docs --directory=docs bash -c 'make clean html SPHINXOPTS="-W --keep-going -n"'
