# Regular QA workflow (pull requests, main branch)

name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  doc-build:
    uses: ./.github/workflows/doc-build.yml
