# Regular QA workflow (pull requests, main branch)

name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
