# Run the unit tests against several pythons and platforms
# using a pre-built wheel artifact to install the package.

name: Test wheel

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build-wheel:

    uses: ./.github/workflows/build-wheel.yml

  test-wheels:

    needs: [build-wheel]

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout unit tests
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            tests
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: File listing
        run: ls -R
      - name: Fetch built wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-artifact
          path: dist
      - name: File listing
        run: ls -R
      - name: Install wheel
        run: |
          python -m pip install dist/*.whl
      - name: Run unittests
        run: |
          python -m unittest discover -v
